### ISSUE TITLE
UCARP Error: Unable to find MAC address of [vtnet1]

### ISSUE THREAD

**Issue by pshanmu** [vpetersson/pg_ha#1]
Hi,

I am working on the setting up the Postgres Cluster on FreeBSD. - Following the procedure in

https://github.com/vpetersson/pg_ha/wiki/Setup-On-FreeBSD

But I am stuck in the starting (basic itself) - ucarp error

tdb1 ucarp[73525]: [ERROR] Unable to find MAC address of [vtnet1]

Please help.
- Shanmu

**Comment by vpetersson** [comment]
I haven't seen that error before, but I haven't touched this script in a while. 

There appears to be a bug in FreeBSD 9 (see [this](http://comments.gmane.org/gmane.comp.clustering.ucarp.general/181) and [this](http://blog.gmane.org/gmane.comp.clustering.ucarp.general/month=20120301)). Hopefully that will point you in the right direction.
